import { effectiveManualTopic } from "@/lib/manual-topic";
import type { TestQuestion } from "@/lib/types";

function normalizeQuestionText(text: string) {
  return text.trim().toLowerCase().replace(/\s+/g, " ");
}

function normToken(value: string) {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}

function parseUavTtxQuestionText(text: string): { title: string; specKey: string } | null {
  const match = text.match(/У БПЛА «([^»]+)» в ТТХ указано значение параметра «([^»]+)»/i);
  if (!match) return null;
  return { title: normToken(match[1] ?? ""), specKey: normToken(match[2] ?? "") };
}

function uavTtxSemanticKey(title: string, specKey: string) {
  return `${title}:${specKey}`;
}

function isAutoGeneratedUavQuestion(id: string) {
  return id.startsWith("uav-q:");
}

/** Убирает повторы по тексту; при совпадении оставляет автогенерацию из каталога БПЛА. */
export function dedupeTestQuestionsByText(questions: readonly TestQuestion[]): TestQuestion[] {
  const seen = new Map<string, TestQuestion>();
  for (const question of questions) {
    const key = normalizeQuestionText(question.text);
    if (!key) continue;
    const existing = seen.get(key);
    if (!existing) {
      seen.set(key, question);
      continue;
    }
    if (isAutoGeneratedUavQuestion(question.id) && !isAutoGeneratedUavQuestion(existing.id)) {
      seen.set(key, question);
    }
  }
  return [...seen.values()];
}

/** Собирает итоговый банк для теста: только ручной или ручной + автогенерация. */
export function buildTestQuestionPool(
  dbPool: readonly TestQuestion[],
  fromUav: readonly TestQuestion[],
  uavAutoGeneration: boolean,
): TestQuestion[] {
  const manualPool = dedupeTestQuestionsByText(dbPool);
  if (!uavAutoGeneration || fromUav.length === 0) return manualPool;
  return mergeUavAutoAndManualQuestionPools(fromUav, manualPool);
}

/** Объединяет автогенерацию из ТТХ БПЛА с ручным банком без дублей по id, тексту и паре «БПЛА + параметр». */
export function mergeUavAutoAndManualQuestionPools(
  fromUav: readonly TestQuestion[],
  dbPool: readonly TestQuestion[],
): TestQuestion[] {
  const autoIds = new Set(fromUav.map((q) => q.id));
  const autoTexts = new Set(fromUav.map((q) => normalizeQuestionText(q.text)).filter(Boolean));
  const autoSemantic = new Set<string>();
  for (const question of fromUav) {
    const parsed = parseUavTtxQuestionText(question.text);
    if (parsed) autoSemantic.add(uavTtxSemanticKey(parsed.title, parsed.specKey));
  }

  const manualFiltered = dbPool.filter((question) => {
    if (autoIds.has(question.id)) return false;
    const normalizedText = normalizeQuestionText(question.text);
    if (normalizedText && autoTexts.has(normalizedText)) return false;
    if (effectiveManualTopic(question) === "uav_ttx") {
      const parsed = parseUavTtxQuestionText(question.text);
      if (parsed && autoSemantic.has(uavTtxSemanticKey(parsed.title, parsed.specKey))) return false;
    }
    return true;
  });

  return dedupeTestQuestionsByText([...fromUav, ...manualFiltered]);
}
